name: Deploy

on:
  workflow_run:
    workflows: [ "Build" ]
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    name: Deploy
    runs-on: ubuntu-latest
    
    # Deploy and release to Azure.
    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "chatGPT"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9B1B326C1381412DB67115FFDC74564F }}
          images: ghcr.io/${{ github.repository }}:${{ steps.sha_tag.outputs.tag }}
