# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatGPT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f2004e235542456bb5cd79614e973f55 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d0c7e4d23134958b2a3cbb2d60a63d0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f2004e235542456bb5cd79614e973f55 }}/rmenai/chatgpt-bot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatGPT'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9b1b326c1381412db67115ffdc74564f }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f2004e235542456bb5cd79614e973f55 }}/rmenai/chatgpt-bot:${{ github.sha }}'